services:
  - type: web
    name: blog-backend
    env: node
    plan: free
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URL
        fromEnvVar: MONGO_URL
      - key: PORT
        value: 5001
